/** @format */

import fetchUser from "@/api/UserManagement/fetchUser";
import { Navbar } from "@/components/NavBar";
import { redirect } from "next/navigation";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data: user } = await fetchUser();

  if (!user) redirect("/login");

  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
